#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

in="$(cat)"
version="$(echo "$in" | jq .version)"
build_number="$(echo "$in" | jq .version.build_number)"

echo "{
  \"version\": $version,
  \"metadata\": [
    { \"name\": \"build_number\", \"value\": $build_number }
  ]
}" | jq . >&3

